"""Constants for the alert light program."""
import board

# Constants
LED_COUNT = 100
LED_PIN = board.D18
LED_BRIGHTNESS = 0.1
ALERT_LENGTH = int(3)
COLOR_ACTIVE_TIME = 600
ALERT_TOKENS = 35
ANIMATION_SPEED = 0.01
MAX_RETRY_DELAY = 60
RETRY_FACTOR = 2
INITIAL_RETRY_DELAY = 2
TIMEOUT_BUFFER_FACTOR = 2
RAINBOW_PERIOD = 60
RAINBOW_SPEED = 0.01
SPARKLE_PERIOD = 60
SPARKLE_SPEED = 0.1
SPARKLE_NUM_SPARKLES = 5
SPARKLE_BRIGHTNESS = 0.5
PULSE_PERIOD = int(ALERT_LENGTH * 2 / 3)
PULSE_PERIOD = 1 if PULSE_PERIOD < 1 else PULSE_PERIOD
PULSE_SPEED = 0.01
ONE_MINUTE = 60
